version: 2.1

jobs:
  linuxkit_dm-crypt:
    docker:
      - image: linuxkit/dm-crypt:v0.7
    steps:
      - checkout
      - run:
          command: |
            bash --version | head -2
            df --version | head -2 || true
            bash ./install.sh
            command -v bats
            bash -c 'PATH="/usr/bin:${PATH}" bin/bats test'
workflows:
  version: 2
  all:
    jobs:
      - linuxkit_dm-crypt
